spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/schedule?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        format_sql: true